export const DINO = {
  stats: { clever: "Clever", fit: "Fit", steady: "Steady" },
  classes: {
    doctor: "The Doctor", engineer: "The Engineer", hunter: "The Hunter",
    kid: "The Kid", paleontologist: "The Paleontologist",
    soldier: "The Soldier", smuggler: "The Smuggler", survivor: "The Survivor",
  },
  classTaglines: {
    doctor:         "You save lives. It's your blessing when you succeed and your curse when you fail.",
    engineer:       "There's no problem humans can't solve with ingenuity and a bit of elbow grease. Even this one.",
    hunter:         "You've hunted most things that can hunt you, but the way these things move…",
    kid:            "You're just a kid!",
    paleontologist: "You've studied dinosaurs by their fossil traces—will that knowledge keep you safe from the real thing?",
    soldier:        "You are a warrior by profession, but is your training enough to best a foe honed by 179 million years of evolution?",
    smuggler:       "You've done a bit of smugglin', and you've run your share of grass.",
    survivor:       "You are not from here, but you've survived alone on the island for a long time.",
  },
  classStories: {
    doctor:         ["Why you became a doctor","A time you were terrified","A nearly fatal mistake","When someone miraculously pulled through","How you blow off steam"],
    engineer:       ["Something inefficient that infuriates you","Something that's perfectly designed","The thing you dream of building","A moment of simple pleasure","A time you were forced to cut corners"],
    hunter:         ["Your most impressive catch","A time you were lost in the wilderness","One way animals outclass people","The strangest food you've eaten","Something an idiot did that got them killed"],
    kid:            ["A time you were really brave","The most annoying thing your parent does","An explanation of something baffling to adults","Something cool a friend taught you","What you're secretly scared of"],
    paleontologist: ["How you fell in love with dinosaurs","Why your arch-rival is a hack","A thing you've never understood about people","A life lesson your mentor taught you","The story behind the fossil you carry"],
    soldier:        ["The time you cheated death","Why you enlisted","An inside joke you shared with your squad","Something that haunts you","A superstition that keeps you alive"],
    smuggler:       ["A close call with the law","How you ruined things with the love of your life","A buddy who met a bad end","Your wildest bender","Your retirement plans"],
    survivor:       ["A useful survival skill you learned here","The person you hope to be reunited with","The mundane comfort you miss most","What you'll do differently if you get off the island","The thing about the island you actually like"],
  },
  classGear: {
    doctor:         ["First aid kit","Penlight","A container of pain pills"],
    engineer:       ["Toolkit (Screwdriver, duct tape, etc.)","Tablet w/durable case","Headlamp"],
    hunter:         ["Tranquilizer rifle (5 darts) OR Hunting bow (10 arrows)","Camouflaged clothing","Hunting knife","A bag of jerky"],
    kid:            ["Toy dinosaur","Swiss army knife","A candy bar + can of soda"],
    paleontologist: ["Basic excavation tools","Bandana","Canteen","Small fossil with sentimental value"],
    soldier:        ["Assault Rifle","Handgun","Flashlight","Combat knife","One extra clip"],
    smuggler:       ["Keys to your vehicle","Forged documents","Innocuous object with a hidden compartment","Flask","Guitar"],
    survivor:       ["Spear","Camouflaged rags","Edible plants","Old backpack","A terrible stench"],
  },
  perilMoves: [
    { key: "run",         label: "Run!",                  stat: "fit"  },
    { key: "hide",        label: "Hide!",                 stat: "clever" },
    { key: "justDoIt",    label: "Just Do It!",           stat: "steady" },
    { key: "holdOn",      label: "Hold On To Your Butt!", stat: "fit"  },
    { key: "lookOver",    label: "Look Over There!",      stat: "clever" },
    { key: "takeMyHand",  label: "Take My Hand!",         stat: "best" },
    { key: "fight",       label: "Fight!",                stat: "none", bonus: 1 },
  ],
  safetyMoves: [
    { key: "layOfTheLand", label: "Lay of the Land",     stat: "clever" },
    { key: "instruct",     label: "Instruct",             stat: "steady" },
    { key: "scavenge",     label: "Scavenge",             stat: "clever" },
    { key: "bestLaidPlans",label: "The Best-Laid Plans",  stat: "none"  },
  ],
};
